# fly.toml app configuration file generated for projetzoo-bold-sun-5371 on 2024-11-26T17:51:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "projetzoo-bold-sun-5371"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443